### ISSUE TITLE
might be better to make the default project directory not a random temp directory

### ISSUE THREAD

**Issue by admahood** [earthlab/firedpy#5]

**Comment by admahood** [comment]
@maxwellCcook check out this dope issue

**Comment by maxwellCcook** [comment]
@admahood what do you think about making the temporary directory within the git clone project folder or just outside of it? Or would that not work because some people will be using this through the docker and thus not have a local clone? If that is the case, where do we want the default output folder (i.e. if a proj_dir is not defined)?

**Comment by admahood** [comment]
@maxwellCcook I'm thinking probably better to do it within the top directory of the git clone, like just data or proj (but also ensure that whatever directory that is is in the .gitignore file

**Comment by admahood** [comment]
e.g. firedpy/proj

**Comment by admahood** [comment]
It would work the same in docker so no worries there

**Comment by maxwellCcook** [comment]
Copy that. Good to know the functionality is the same in the Docker then. I'll set default to firedpy/proj or firedpy/outputs

**Comment by maxwellCcook** [comment]
testing it now to see if this issue is resolved in my branch
